ARG base=runtime
ARG comfy_version=0.3.67
ARG pytorch_version=2.8.0
ARG cuda_version=12.6

FROM ghcr.io/saladtechnologies/comfyui-api:comfy${comfy_version}-torch${pytorch_version}-cuda${cuda_version}-${base}

ENV WORKFLOW_DIR=/workflows
ENV STARTUP_CHECK_MAX_TRIES=30

# Copy the locally built binary
COPY bin/comfyui-api .

RUN chmod +x comfyui-api

CMD ["./comfyui-api"]
