FROM ghcr.io/saladtechnologies/comfyui-api:comfy0.8.2-torch2.8.0-cuda12.6-runtime

COPY test/docker-image/dreamshaper_8.safetensors $MODEL_DIR/checkpoints/dreamshaper_8.safetensors

COPY bin/comfyui-api /comfyui-api
RUN chmod +x /comfyui-api

ENV LOG_LEVEL=debug

CMD ["/comfyui-api"]