ARG comfy_image=ghcr.io/saladtechnologies/comfyui-api:comfy0.35.0-torch2.13.0-cuda13.0-runtime
FROM ${comfy_image}

COPY test/workflow-endpoints /workflows
COPY test/workflows /test-workflows

ENV WORKFLOW_DIR=/workflows
ENV WARMUP_PROMPT_FILE=/test-workflows/sd1.5-txt2img.json
ENV STARTUP_CHECK_MAX_TRIES=120

CMD ["/test-bin/comfyui-api"]
