#! /usr/bin/bash
set -euo pipefail

comfy_version=${1:-0.35.0}
torch_version=${2:-2.13.0}
cuda_version=${3:-13.0}
bases=("devel" "runtime")

for base in "${bases[@]}"; do
  docker build -t ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-torch$torch_version-cuda$cuda_version-$base \
    -f comfyui.dockerfile \
    --no-cache \
    --build-arg comfy_version=$comfy_version \
    --build-arg base=$base \
    --build-arg pytorch_version=$torch_version \
    --build-arg cuda_version=$cuda_version \
    .
done
