#! /usr/bin/bash

usage="Usage: $0 [comfy_version] [torch_version] [cuda_version] [api_version]"

comfy_version=${1:-0.8.2}
torch_version=${2:-2.8.0}
cuda_version=${3:-12.6}

current_api_version=$(cat ../package.json | jq -r '.version')
api_version=${4:-$current_api_version}

bases=("devel" "runtime")

for base in "${bases[@]}"; do
  docker build -t ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-api$api_version-torch$torch_version-cuda$cuda_version-$base \
    -f api.dockerfile \
    --build-arg comfy_version=$comfy_version \
    --build-arg base=$base \
    --build-arg pytorch_version=$torch_version \
    --build-arg cuda_version=$cuda_version \
    --build-arg api_version=$api_version \
    .
  docker push ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-api$api_version-torch$torch_version-cuda$cuda_version-$base

  if [ $base == "runtime" ]; then
    docker tag ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-api$api_version-torch$torch_version-cuda$cuda_version-runtime ghcr.io/saladtechnologies/comfyui-api:latest
    docker push ghcr.io/saladtechnologies/comfyui-api:latest
    docker image rm ghcr.io/saladtechnologies/comfyui-api:latest
  fi

   # Remove the image to make space for the next one. Github actions runners don't get much storage.
  docker image rm ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-api$api_version-torch$torch_version-cuda$cuda_version-$base
done
