#! /usr/bin/bash

usage="Usage: $0 [comfy_version] [torch_version] [cuda_version]"

comfy_version=${1:-0.8.2}
torch_version=${2:-2.8.0}
cuda_version=${3:-12.6}

bases=("devel" "runtime")

for base in "${bases[@]}"; do
  docker push ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-torch$torch_version-cuda$cuda_version-$base
done

docker tag ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-torch$torch_version-cuda$cuda_version-runtime ghcr.io/saladtechnologies/comfyui-api:base
docker push ghcr.io/saladtechnologies/comfyui-api:base