#! /usr/bin/bash

usage="Usage: $0 [comfy_version] [torch_version] [cuda_version] [api_version]"

comfy_version=${1:-0.3.10}
torch_version=${2:-2.5.0}
cuda_version=${3:-12.1}

current_api_version=$(cat ../package.json | jq -r '.version')
api_version=${4:-$current_api_version}

bases=("devel" "runtime")

for base in "${bases[@]}"; do
  docker push ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-api$api_version-torch$torch_version-cuda$cuda_version-$base
done

docker tag ghcr.io/saladtechnologies/comfyui-api:comfy$comfy_version-api$api_version-torch$torch_version-cuda$cuda_version-runtime ghcr.io/saladtechnologies/comfyui-api:latest
docker push ghcr.io/saladtechnologies/comfyui-api:latest